### ISSUE TITLE
(Android) Repeated microphone notification 📵🎙🤓

### ISSUE THREAD

**Issue by revett** [TalAter/annyang#194]
> Works perfectly on desktop.

When using **Annyang** on my my Android in Chrome, the microphone notification repeatedly goes off when accessing the site over HTTPS.

If I access it over HTTP, it allows me to complete a command, and then asks me to Block/Allow the use of the microphone again.

I **would like** to use HTTPS so it remembers my choice.
## Expected Behavior
- First time visiting site should ask for permission to use microphone and should remember my choice.
- When loading the site should make microphone notification noise once.
- Should then not make the notification noise again.
## Current Behavior
- First time visiting site, asks for permission to use microphone and remembers choice.
- Then repeatedly (every 1-2 seconds) makes microphone notification noise.
## Possible Solution

**Maybe** using the `.start()` options:

``` js
annyang.start({ autoRestart: false });
annyang.start({ autoRestart: false, continuous: false });
```
## Steps to Reproduce (for bugs)

``` js
$(function() {
  if (annyang) {
    var commands = {
      'hello': function() {
        someFunction();
      },
      'light on': function() {
        someFunction();
      },
      'lights on': function() {
        someFunction();
      },
      'light off': function() {
        someFunction();
      },
      'lights off': function() {
        someFunction();
      }
    };

    annyang.addCommands(commands);
    annyang.start();
  }
});
```
## Your Environment
- Version: `2.3.0`
- Chrome: `49.0.2623.105`
- Operating System: `Android 5.1.1`

Thanks! ✌️

**Comment by lmangani** [comment]
Hi @revett 
Out of preliminary curiosity, are you using a valid certificate on the server?

**Comment by revett** [comment]
Hi @lmangani 👋 

Thanks for the quick reply. Yep, its backed by the **GlobalSign Root CA** and is accepted in Chrome (green).

**Comment by revett** [comment]
@TalAter any ideas?

**Comment by lmangani** [comment]
Is this resource publicly available for others to try test/replicate for suggestions?

**Comment by revett** [comment]
@lmangani - tested on two devices, using the same version of Annyang.

**Comment by revett** [comment]
@lmangani - I could make a replica if 100% needed.

**Comment by atchyut-re** [comment]
This is fixed and the behavior on mobile with respect to remembering the user's permission is the same as on desktop from M33 for Chrome on Android.

Ref:  https://code.google.com/p/chromium/issues/detail?id=274022&can=1&q=webrtc%20permission&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

**Comment by revett** [comment]
@atchyut-re nice spot! Do you know the Chrome version it was released on?

**Comment by atchyut-re** [comment]
Sorry, @revett  I had no idea.

**Comment by TalAter** [comment]
Thanks @atchyut-re 👍 

Unfortunately, the issue of the microphone notification noise triggering over and over again is still a problem with Chrome for Android.

**Comment by namel** [comment]
@TalAter - Eventually I switched to native webkitSpeechRecognition -  :(
when I use the native API I get almost no notification noises.

**Comment by revett** [comment]
@namel so you stopped using annyang?

**Comment by TalAter** [comment]
@namel Could you share your code? If I could see what you are doing different, we may find a hint for the problem.

Thanks :+1:

**Comment by namel** [comment]
@TalAter 

My code isn't neatly organized - but the jist of it is that I needed to start and stop and specific points in time.  And once it restarted, it had to remain continuous.

As I re-read the annyang API, it seems like I could have done this with `start({continuous:true})`,  `pause()` and `resume()`.

The real problem is that I mistakenly thought I could do better than Annyang on android because I was seeing good results on my mac.  Maybe if the documentation was more explicit then I wouldn't have gone down that path?  For example if you mentioned that on Android+continuous there are notification noises, (because the underlying API implementation doesn't support true continuous) and one potential mitigation is to use pause/resume in relevant places.

**Comment by atchyut-re** [comment]
@namel I had tried what you have mentioned in the above comment. But unfortunately the problem still occuring.
Can you please a code sample if it is working fine with you.
Thankyou :+1:

**Comment by namezero** [comment]
same problem here, doesnt works on android chrome

**Comment by namezero** [comment]
**repeatedly (every 1-2 seconds) makes microphone notification noise.**
i have chrome 53.0.2785.124
android 5.0.0

**Comment by mwkrieger** [comment]
I'm seeing this same exact behavior and it seems to be related to #206

**Comment by filippoo** [comment]
I got stuck on the same issue :( 
Since annyang is a victim rather than the cause here, has anyone tried reaching out to google/chromium folks? The issue occurs on a combination of Google OS + Google API + Google browser. :) I used Android 6 with Chrome 50.

BTW - I wouldn't say that switching to webkitSpeechRecognition helps, I am getting exactly the same issue, I am not sure how others made it to work - if you succeeded, please kindly share how.

**Comment by bheijns** [comment]
Same issue here (cordova / crosswalk). Workaround: make it event-driven but that's not an actual solution. Should be fixed in Chrome/Chromium.

**Comment by confidence68** [comment]
mobile is not support it? why i use it no response！

`			$(document).ready(function(){
				$(".tab_content").hide();
				$(".tab_content:first").show();
				$('ul.tabs li').last().addClass("tab_last");

				$("ul.tabs li").click(function() {
					
					$(".tab_content").hide();
					$(".tab_content").eq($(this).index()).show();
	
					$("ul.tabs li").removeClass("active");
					$(this).addClass("active");
	
				});
	
				

			  // first we make sure annyang started succesfully
			  if (annyang) {
			    
			    // define the functions our commands will run.
			    var showNews=function(){
			    	$(".tab_content").hide();
					$(".tab_content").eq(0).show();
					
					$("ul.tabs li").removeClass("active");
					$("ul.tabs li").eq(0).addClass("active");
			    };
			    var showNotices=function(){
			    	$(".tab_content").hide();
					$(".tab_content").eq(1).show();
					
					$("ul.tabs li").removeClass("active");
					$("ul.tabs li").eq(1).addClass("active");
			    };
			    var showGonggao=function(){
			    	$(".tab_content").hide();
					$(".tab_content").eq(2).show();
					
					$("ul.tabs li").removeClass("active");
					$("ul.tabs li").eq(2).addClass("active");
			    };
			    var showNote=function(){
			    	$(".tab_content").hide();
					$(".tab_content").eq(3).show();
					
					$("ul.tabs li").removeClass("active");
					$("ul.tabs li").eq(3).addClass("active");
			    };
			
			    var getStarted = function() {
			      window.location.href = 'https://github.com/TalAter/annyang';
			    };
			
			    // define our commands.
			    // * The key is what you want your users to say say.
			    // * The value is the action to do.
			    //   You can pass a function, a function name (as a string), or write your function as part of the commands object.
			    var commands = {
			      '新闻':	showNews,
			      '通知':	showNotices,
			      '公告':	showGonggao,
			      '备注':	showNote,
			    };
			
			    // OPTIONAL: Set a language for speech recognition (defaults to English)
			    annyang.setLanguage('zh-cn');
			    // OPTIONAL: activate debug mode for detailed logging in the console
			    annyang.debug();		
			    // Add voice commands to respond to
			    annyang.addCommands(commands);			
			    // Start listening. You can call this here, or attach this call to an event, button, etc.
			    annyang.start();
			  }
				
			})	`

**Comment by scamianbas** [comment]
Same behaviour here with Annyang as well as with the SpeechRecognition API (chrome 54.0.2840.85 / Android 5.1.1). Tested with https://www.talater.com/annyang/ and https://davidwalsh.name/demo/speech-recognition-video.php

**Comment by sgasser** [comment]
No chrome issue found.

Opened one https://bugs.chromium.org/p/chromium/issues/detail?id=679010

Please add a comment if something is missing

:star: this chrome issue - thanks

**Comment by Thread7** [comment]
This happens for me as well.  It is only for Chrome on Android.  Does anyone know of an alternative browser that can work on Android?  I tried mobile Firefox but it must not support speech recognition.

**Comment by javismiles** [comment]
Any news about this? The current non stop beeping makes it all completely unusable on android phones, crossing fingers for a solution eventually, thank you for this great library by the way, all best

**Comment by mulyoved** [comment]
maybe related to this 4 year android issue?

https://code.google.com/p/android/issues/detail?id=37862

**Comment by Thread7** [comment]
I would encourage everyone to make comments in those Google forums so we can get this fixed once and for all.

**Comment by Nemesis24** [comment]
Sorry for my "bad" english, it seems here https://syl22-00.github.io/pocketsphinx.js/live-demo.html the problem was not encountered with my android phone.

perhaps a way to find a solution @Talaler

**Comment by vin-ni** [comment]
got the same problem

**Comment by rmd97** [comment]
I used the volumen control,  When the page is open  I put the volumen in 0, When leave the page I put the volumen in 1.

**Comment by ardakazanci** [comment]
How did you work on Android. I could not run it on WebView. Can you help me?

**Comment by macdonst** [comment]
@ardakazanci the Android WebView does not include the speech rec API IIRC.

**Comment by ardakazanci** [comment]
@macdonst  What are the alternatives?

**Comment by macdonst** [comment]
@ardakazanci you could use Cordova and then add my Speech Rec plugin into the app. YMMV with the plugin as I haven't had much time to work on it recently but it does add the speech rec api into the web view and you can run annyang on top of it.

https://github.com/macdonst/SpeechRecognitionPlugin

**Comment by ardakazanci** [comment]
I live with this problem. How can I resolve

**Comment by rmd97** [comment]
I cant' resolve it.


I down the volumen.



________________________________
De: Arda Kazancı <notifications@github.com>
Enviado: domingo, 13 de agosto de 2017 02:45 a. m.
Para: TalAter/annyang
CC: rmd97; Comment
Asunto: Re: [TalAter/annyang] (Android) Repeated microphone notification 📵🎙🤓 (#194)


I live with this problem. How can I resolve

**Comment by jbreckmckye** [comment]
The Chrome team have marked the issue as 'wontFix':

> Yes, I have run the demo https://www.talater.com/annyang/ on an android mobile phone.
That web page is continually using speech recognition.
This API is not intended for continuous use in this manner.
This is working as intended.
-- gshires@chromium.org

This issue appears to be unresolvable. : /

**Comment by ardakazanci** [comment]
Any progress?

**Comment by TalAter** [comment]
No. As detailed in https://github.com/TalAter/annyang/issues/194#issuecomment-323775236 this appears to be a design choice by Google.

**Comment by kylebakerio** [comment]
So, to be clear, this is still the case? I wish this were clearly stated in the library documentation around continuous, or anywhere. I was basing a design on this idea, and I finally got it working only to have this issue, google it, and read the thread all the way to the bottom.

**Comment by vin-ni** [comment]
@kylebakerio  It seems so. On the other hand, you're using the free speech from google chrome. If you don't mind paying for the speech rec, I've built a base for a node based speech rec that works on any device and cross browser: 
https://github.com/vin-ni/Google-Cloud-Speech-Node-Socket-Playground
